syntax = "proto2";

import "yt/yt_proto/yt/formats/extension.proto";
import "scarab/api/proto/common/options.proto";
import "scarab/api/proto/common/compat.proto";
import "scarab/api/proto/report/search_props/UPPER/adv.proto";
import "scarab/api/proto/report/search_props/UPPER/blender.proto";
import "scarab/api/proto/report/search_props/UPPER/images.proto";
import "scarab/api/proto/report/search_props/UPPER/misc.proto";
import "scarab/api/proto/report/search_props/UPPER/root.proto";
import "scarab/api/proto/report/search_props/UPPER/rtx.proto";
import "scarab/api/proto/report/search_props/UPPER/stateful.proto";
import "scarab/api/proto/report/search_props/UPPER/turbo.proto";
import "scarab/api/proto/report/search_props/UPPER/video.proto";
import "scarab/api/proto/report/search_props/UPPER/wizards.proto";

package NScarabProto.NReport.NSearchProps.NUPPER;
option go_package = "a.yandex-team.ru/scarab/api/proto/report/search_props/go/UPPER";
// Source definition
message TSource {
    option (NYT.default_field_flags) = SERIALIZATION_YT;
    option (NYT.default_field_flags) = OPTIONAL_LIST;

    optional TPropAfishaEventWizardUpper AfishaEventWizardUpper = 1;
    optional TPropAfishaHighlight AfishaHighlight = 2;
    optional TPropAliceWizard AliceWizard = 3;
    optional TPropAntiDup AntiDup = 4;
    optional TPropApplyBlender ApplyBlender = 5 [(_owner_fld) = "abc:blender", (_ttl) = 360];
    optional TPropApplyBlender ApplyImagesBlender = 6 [(_owner_fld) = "abc:blender", (_ttl) = 360];
    optional TPropApplyBlender ApplyVideoBlender = 7 [(_owner_fld) = "abc:blender", (_ttl) = 360];
    optional TPropArknight Arknight = 8;
    optional TPropAvia Avia = 9;
    optional TPropBanner Banner = 10;
    optional TPropBannerTurbo BannerTurbo = 11;
    optional TPropBannerTurboFeedback BannerTurboFeedback = 12;
    optional TPropBigNavAnswerUpper BigNavAnswerUpper = 13 [(_owner_fld) = "abc:sitelinksbna"];
    optional TPropBlenderDssmFeatures BlenderDssmFeatures = 14;
    optional TPropBlenderFmls BlenderFmls = 15;
    optional TPropBlenderMetaFeatures BlenderMetaFeatures = 16;
    optional TPropBlenderNeocortexFeatures BlenderNeocortexFeatures = 17;
    optional TPropBlenderOnlineLearning BlenderOnlineLearning = 18;
    optional TPropBlenderSnippetFeatures BlenderSnippetFeatures = 19;
    optional TPropBlenderUpperCache BlenderUpperCache = 20;
    optional TPropBlenderWebFeatures BlenderWebFeatures = 21;
    optional TPropChatFilter ChatFilter = 22;
    optional TPropChatWizard ChatWizard = 23;
    optional TPropCollectionsBoardsRtx CollectionsBoardsRtx = 24;
    optional TPropCollectionsBoardsSerpData CollectionsBoardsSerpData = 25;
    optional TPropCollectionsBoardsSerpDataRtx CollectionsBoardsSerpDataRtx = 26;
    optional TPropCompetitorFilter CompetitorFilter = 27;
    optional TPropContextVerticals ContextVerticals = 28;
    optional TPropCoronavirus Coronavirus = 29;
    optional TPropDirectMarket DirectMarket = 30;
    optional TPropDirectWizard DirectWizard = 31;
    optional TPropDoc2Group Doc2Group = 32;
    optional TPropEda Eda = 33;
    optional TPropElection Election = 34;
    optional TPropEntitySearch EntitySearch = 35;
    optional TPropEraseRightColumn EraseRightColumn = 36;
    optional TPropFConsole FConsole = 37;
    optional TPropFacts Facts = 38;
    optional TPropFamilyFilter FamilyFilter = 39;
    optional TPropFormulaLog FormulaLog = 40;
    optional TPropFresh Fresh = 41;
    optional TPropFreshManual FreshManual = 42;
    optional TPropGames Games = 43;
    optional TPropHealth Health = 44;
    optional TPropHighlightDocuments HighlightDocuments = 45;
    optional TPropHiliteUrl HiliteUrl = 46;
    optional TPropHiliter Hiliter = 47;
    optional TPropHostClassifier HostClassifier = 48;
    optional TPropBlenderFmls ImgBlenderFmls = 49;
    optional TPropImgFresh ImgFresh = 50;
    optional TPropImgPornoUpper ImgPornoUpper = 51;
    optional TPropImgSerpData ImgSerpData = 52;
    optional TPropIznankaDivFormat IznankaDivFormat = 53;
    optional TPropL1 L1 = 54 [(_compat_renamed_from) = "", (_split_size_limit) = 200];
    optional TPropLanding Landing = 55;
    optional TPropMarketUpper MarketUpper = 56;
    optional TPropMisspell Misspell = 57;
    optional TPropMushroomMediaBanner MushroomMediaBanner = 58;
    optional TPropNewsFromQuickUpper NewsFromQuickUpper = 59;
    optional TPropNewsPersonalFeed NewsPersonalFeed = 60;
    optional TPropOrgWizard OrgWizard = 61 [(_owner_fld) = "abc:geosearch", (_ttl) = 180, (_rt_required) = false];
    optional TPropOscar Oscar = 62;
    map<string, string> Pager = 63;
    optional TPropPersonalization Personalization = 64;
    optional TPropPhoneNumberCheck PhoneNumberCheck = 65;
    optional TPropPornoUpper PornoUpper = 66 [(_infinite_ttl) = true];
    optional TPropPressportret Pressportret = 67;
    optional TPropPrettySerpFeatures PrettySerpFeatures = 68;
    optional TPropPrettySerpFeaturesPrepare PrettySerpFeaturesPrepare = 69;
    optional TPropPrettySerpFeaturesRtx PrettySerpFeaturesRtx = 70;
    optional TPropRabota Rabota = 71;
    optional TPropRandomLog RandomLog = 72;
    optional TPropRasp Rasp = 73;
    optional TPropRearrangeIznanka RearrangeIznanka = 74;
    optional TPropRepSnipAdresa RepSnipAdresa = 75;
    optional TPropRepSnipSpecialDates RepSnipSpecialDates = 76;
    optional TPropRepWizMisspell RepWizMisspell = 77;
    optional TPropRepWizRegion RepWizRegion = 78;
    optional TPropRepWizRequestExtensions RepWizRequestExtensions = 79 [(_owner_fld) = "abc:shinydiscovery"];
    optional TPropRightColumnTransport RightColumnTransport = 80;
    optional TPropRoot Root = 81 [(_compat_renamed_from) = ""];
    optional TPropSerpFact SerpFact = 82;
    optional TPropSerpObject SerpObject = 83;
    optional TPropShinyDiscovery ShinyDiscovery = 84;
    optional TPropSingleOrgMx SingleOrgMx = 85;
    optional TPropSitelinks Sitelinks = 86 [(_owner_fld) = "abc:sitelinksbna"];
    optional TPropSnippetLogging SnippetLogging = 87;
    optional TPropSwapN SwapN = 88;
    optional TPropTVTranslations TVTranslations = 89;
    optional TPropTalents Talents = 90;
    optional TPropTasix Tasix = 91;
    optional TPropToponymWizard ToponymWizard = 92 [(_owner_fld) = "abc:geosearch", (_ttl) = 180, (_rt_required) = false];
    optional TPropTransport Transport = 93;
    optional TPropTrends Trends = 94;
    optional TPropTurboSnippet TurboSnippet = 95;
    optional TPropTurboSnippet TurboSnippetRight = 96;
    optional TPropTurboUrls TurboUrls = 97;
    optional TPropTutor Tutor = 98;
    optional TPropUgc Ugc = 99;
    optional TPropUgcFavorites UgcFavorites = 100;
    optional TPropUniAnswer UniAnswer = 101;
    optional TPropUpperImgMisspell UpperImgMisspell = 102;
    optional TPropUserGroupingsLoad UserGroupingsLoad = 103;
    optional TPropVectorPersonalization VectorPersonalization = 104;
    optional TPropVertical Vertical = 105;
    optional TPropVerticalCardUpperValidation VerticalCardUpperValidation = 106;
    optional TPropVideo Video = 107;
    optional TPropVideoAntidupFinal VideoAntidupFinal = 108;
    optional TPropVideoAntiobject VideoAntiobject = 109;
    optional TPropBlenderFmls VideoBlenderFmls = 110;
    optional TPropVideoCheatUrls VideoCheatUrls = 111;
    optional TPropVideoDupsMiddle VideoDupsMiddle = 112;
    optional TPropVideoDupsMiddle VideoDupsUpper = 113;
    optional TPropVideoFastDeliveryUpper VideoFastDeliveryUpper = 114;
    optional TPropVideoRecommender VideoRecommender = 115;
    optional TPropVideoSerialUpper VideoSerialUpper = 116;
    optional TPropVideoSerpdata VideoSerpdata = 117;
    optional TPropVideoSvodUpper VideoSvodUpper = 118;
    optional TPropVideohostingWizard VideohostingWizard = 119;
    optional TPropWebCache WebCache = 120;
    optional TPropWizardCarousel WizardCarousel = 121;
    optional TPropWizardRulesLog WizardRulesLog = 122;
    optional TPropYTutorGdzWizard YTutorGdzWizard = 123;
    optional TPropYTutorPdfWizard YTutorPdfWizard = 124;
    optional TPropYdoWizard YdoWizard = 125;
    optional TPropZen Zen = 126 ;
    optional TPropZnatokiAskTheQuestion ZnatokiAskTheQuestion = 127;
    optional TPropZnatokiTeaser ZnatokiTeaser = 128;

    optional TPropPrismBigBLog PrismBigBLog = 129;
    optional TPropEcomOffers EcomOffers = 130;
    optional TPropFilterBannedUpper FilterBannedUpper = 131;
    optional string UserHistoryResponseFiltered = 132 [(_owner_fld) = "abc:searchpers", (_split_size_limit) = 10400];

    optional TPropUnisearchEducation UnisearchEducation = 133;
    optional TPropVideoUgc VideoUgc = 134;
    optional TPropTrash Trash = 135;
    optional TPropFreshVideoClassifier FreshVideoClassifier = 136;
    optional TPropShinyDiscovery ShinyDiscoveryRight = 137;
    optional TPropVideoExtraItems VideoExtraItems = 138;
    optional TPropVideoInsightsUpper VideoInsightsUpper = 139;
    optional TPropVideoDelayedView VideoDelayedView = 140;
    optional TPropVideoChatsData VideoChatsData = 141;
    optional TPropDirectPokupkiGallery DirectPokupkiGallery = 142;
    optional TPropTurboPageChecker TurboPageChecker = 143;
    optional TPropExternal External = 144;
    optional TPropSwapN SwapNOrganic = 145;
    optional TPropUserSurveys UserSurveys = 146;
    optional TPropMergeDocsIntoWiz MergeDocsIntoWiz = 147;
    optional TPropLuaUpper LuaUpper = 148;
    optional TPropSnippetBlender SnippetBlender = 150;
    optional TPropMarkDocAge MarkDocAge = 151;
    optional TPropStocks Stocks = 152;
    optional TPropMarketShopInShop MarketShopInShop = 153;
    optional TPropAviaMiddle AviaMiddle = 154;
    optional TPropSameServicesChecker SameServicesChecker = 155;
    optional TPropVMBP VMBP = 156;
    optional TPropHostBooster HostBooster = 157;
    optional TPropProducts Products = 158 [(_owner_fld) = "abc:goods_runtime", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropCurrencyConverterUpper CurrencyConverterUpper = 159 [(_owner_fld) = "abc:blndr", (_ttl) = 1080];
    optional TPropCardsRanking CardsRanking = 160;
    optional TPropFastres2DataMerge Fastres2DataMerge = 161 [(_owner_fld) = "abc:blender", (_split_size_limit) = 10]; // TODO get rid now
    optional TPropFactsMetadoc FactsMetadoc = 162 [(_owner_fld) = "abc:metadocument"];
    optional TPropFastres2DataMergeV2 Fastres2DataMergeV2 = 163 [(_owner_fld) = "abc:blender", (_compat_renamed_from) = "Fastres2DataMerge"];
    optional TPropCounterpartyWizard CounterpartyWizard = 164 [(_owner_fld) = "abc:rtx", (_split_size_limit) = 1600];
    optional TPropStateful Stateful = 165 [(_owner_fld) = "abc:blender", (_rt_required) = true];
    optional TPropPiraFiltering PiraFiltering = 166;
    optional TPropUnisearchMedicine UnisearchMedicine = 167;
    optional TPropSuppliers Suppliers = 168 [(_owner_fld) = "abc:b2b_product", (_split_size_limit) = 1000];
    optional TPropStaticWizard StaticWizard = 169 [(_owner_fld) = "abc:blender", (_split_size_limit) = 30];
    optional TPropEcomResearch EcomResearch = 170 [(_owner_fld) = "abc:serppolishing", (_split_size_limit) = 0, (_ttl) = 360];
    optional TPropVideoTranslations VideoTranslations = 171;
    optional TPropMobileAppRearrangeRule MobileAppRearrangeRule = 172 [(_owner_fld) = "abc:unisearch", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropVideoRecommenderRvb VideoRecommenderRvb = 173 [(_owner_fld) = "abc:videolog"];
    optional TPropRandomImageGame RandomImageGame = 174 [(_owner_fld) = "abc:blender"];
    optional TPropNewsBlockUpper NewsBlockUpper = 175 [(_owner_fld) = "abc:blender"];
    optional TPropStatefulRecs StatefulRecs = 176 [(_owner_fld) = "abc:stateful_search", (_rt_required) = true];
    optional TPropEducationWizard EducationWizard = 177 [(_owner_fld) = "abc:videoquality"];
    optional TPropSpellchecker Spellchecker = 178 [(_owner_fld) = "abc:spellchecker"];
    optional TPropProgrammingWizard ProgrammingWizard = 179 [(_owner_fld) = "abc:serppolishing"];
    optional TPropSportWizard SportWizard = 180 [(_owner_fld) = "abc:sport", (_rt_required) = true, (_compat_renamed_from) = "SportWizardUpper"];
    optional TPropEcomAdvOwner PropEcomAdvOwner = 181 [(_owner_fld) = "abc:commercial", (_split_size_limit) = 0];
    optional TPropAdsOrganic PropAdsOrganic = 182 [(_owner_fld) = "abc:commercial", (_compat_renamed_from) = "AdsOrganic"];
    optional TPropMoneySource MoneySource = 183 [(_owner_fld) = "abc:images", (_split_size_limit) = 0, (_compat_renamed_from) = ""];
    optional TPropGenerativeAnswer GenerativeAnswer = 184 [(_owner_fld) = "abc:search_generative_answers", (_ttl) = 90, (_rt_required) = true];
    optional TPropMarketExpBlend MarketExpBlend = 185 [(_owner_fld) = "abc:search_play", (_split_size_limit) = 0];
    optional TPropLogIntentSerpDataUpper IntentSerpData = 186 [(_owner_fld) = "abc:blender", (_ttl) = 180, (_split_size_limit) = 0, (_compat_renamed_from) = "LogIntentSerpDataUpper"];
    optional TPropEcomOfflineGenerativeAnswer EcomOfflineGenerativeAnswer = 187 [(_owner_fld) = "abc:ecom_genesis", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropEcomTrafaret EcomTrafaret = 188 [(_owner_fld) = "abc:commercial", (_split_size_limit) = 0, (_ttl) = 0]; // unused
    reserved 189; // was named incorrectly and deleted
    optional TPropVideoUniversalIncut VideoUniversalIncut = 190 [(_owner_fld) = "abc:videoquality", (_split_size_limit) = 0];
    optional TPropEcomComparator EcomComparator = 191 [(_owner_fld) = "abc:ecom_genesis", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropUgcSerpPolls UgcSerpPolls = 192 [(_owner_fld) = "abc:ugc_unisearch_backend", (_split_size_limit) = 0];
    optional TPropEcomPromos EcomPromos = 193 [(_owner_fld) = "abc:goods-blending", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropEcomVendors EcomVendors = 194 [(_owner_fld) = "abc:goods-blending", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropEcomFilters EcomFilters = 195 [(_owner_fld) = "abc:ecom_genesis", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropEcomNeuroG EcomNeuroG = 196 [(_owner_fld) = "abc:goods_runtime", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropEcomNeuroH EcomNeuroH = 197 [(_owner_fld) = "abc:goods_runtime", (_ttl) = 90, (_split_size_limit) = 0];
    optional string ImagesWizardLog = 198 [(_owner_fld) = "abc:images_models_services", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropMetarealty Metarealty = 199 [(_owner_fld) = "abc:metarealty", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropAdsUnisearch PropAdsUnisearch = 200 [(_owner_fld) = "abc:unisearch", (_ttl) = 90, (_split_size_limit) = 0, (_compat_renamed_from) = "AdsUnisearch"];
    optional TPropIntDiscoveryRecommender IntDiscoveryRecommender = 201 [(_owner_fld) = "abc:int_discovery"];
    optional TPropTrNewsWizard TRNewsWizard = 202 [(_owner_fld) = "abc:newstr", (_ttl) = 90];
    optional TPropNamazUpper NamazUpper = 203 [(_owner_fld) = "abc:international_blender", (_ttl) = 90];
    optional TPropEcomComplexChoice EcomComplexChoice = 204 [(_owner_fld) = "abc:ecom_neuro", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropDynamicTabs DynamicTabs = 205 [(_owner_fld) = "abc:unisearch", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropDeliveryTrackingUpper DeliveryTrackingUpper = 206 [(_owner_fld) = "abc:int_search_verticals", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropFilmLists FilmLists = 207 [(_owner_fld) = "abc:videoquality", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropLogSearchProps LogSearchProps = 208 [(_owner_fld) = "abc:upper", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropEcomGroupingUpper EcomGroupingUpper = 209 [(_owner_fld) = "abc:blndr", (_ttl) = 360];
    optional TPropShopsHostsRatings ShopsHostsRatings = 210 [(_owner_fld) = "abc:ugc_unisearch_backend", (_split_size_limit) = 0];
    optional TPropUnisearchServices UnisearchServices = 211 [(_owner_fld) = "abc:uslugi_na_poiske", (_compat_renamed_from) = "UnisearchServices", (_ttl) = 90, (_split_size_limit) = 0];
    optional TPropEcomMergeUpper EcomMergeUpper = 212 [(_owner_fld) = "abc:blndr", (_ttl) = 360];
    optional TPropOlympusOsago OlympusOsago = 213 [(_owner_fld) = "abc:finance_search", (_ttl) = 90];
    optional TPropAdsOrganicPatchDocs PropAdsOrganicPatchDocs = 214 [(_owner_fld) = "abc:commercial", (_compat_renamed_from) = "AdsOrganicPatchDocs"];
    optional TPropBonds Bonds = 215 [(_owner_fld) = "abc:finance_search", (_ttl) = 90];
}
