package NBlenderOnlineLearning.NProto;

import "yt/yt_proto/yt/formats/extension.proto";
option go_package = "a.yandex-team.ru/kernel/blender/online_learning/protos";
message TFloatVector {
    option (NYT.default_field_flags) = SERIALIZATION_YT;
    option (NYT.default_field_flags) = OPTIONAL_LIST;

    repeated float Value = 1 [packed=true];
}

message TFloatMatrix {
    option (NYT.default_field_flags) = SERIALIZATION_YT;
    option (NYT.default_field_flags) = OPTIONAL_LIST;

    repeated TFloatVector Row = 1;
}
