syntax = "proto2";

import "yt/yt_proto/yt/formats/extension.proto";
import "scarab/api/proto/common/options.proto";
import "scarab/api/proto/common/compat.proto";

package NScarabProto.NReport.NSearchProps.NUPPER;
option go_package = "a.yandex-team.ru/scarab/api/proto/report/search_props/UPPER;search_props";
// Props definitions

// TODO protobufize https://a.yandex-team.ru/arc/trunk/arcadia/search/base/yxs_ctxt.cpp
message TPropL1 {
    option (NYT.default_field_flags) = SERIALIZATION_YT;

    optional string FormulaFmlId = 1 [(_compat_renamed_from) = "L1FormulaFmlId", (_split_size_limit) = 15];
    optional string FormulaFmlIdPlatinum0 = 2 [(_compat_renamed_from) = "L1FormulaFmlId_platinum0", (_split_size_limit) = 15];
    optional string FormulaFmlIdQuick = 3 [(_compat_renamed_from) = "L1FormulaFmlId_quick", (_split_size_limit) = 5];
    optional string FormulaFmlIdQuickrt = 4 [(_compat_renamed_from) = "L1FormulaFmlId_quickrt", (_split_size_limit) = 5];
    optional string FormulaFmlIdWebfresh = 5 [(_compat_renamed_from) = "L1FormulaFmlId_webfresh", (_split_size_limit) = 15];
    optional string FormulaIdNewBase = 6 [(_compat_renamed_from) = "L1FormulaId_NewBase", (_split_size_limit) = 65];
    optional string FormulaName = 7 [(_compat_renamed_from) = "L1FormulaName", (_split_size_limit) = 20];
    optional string FormulaNameNewBase = 8 [(_compat_renamed_from) = "L1FormulaName_NewBase", (_split_size_limit) = 20];
    optional string FormulaNamePlatinum0 = 9 [(_compat_renamed_from) = "L1FormulaName_platinum0", (_split_size_limit) = 20];
    optional string FormulaNameQuick = 10 [(_compat_renamed_from) = "L1FormulaName_quick", (_split_size_limit) = 5];
    optional string FormulaNameQuickrt = 11 [(_compat_renamed_from) = "L1FormulaName_quickrt", (_split_size_limit) = 5];
    optional string FormulaNameWebfresh = 12 [(_compat_renamed_from) = "L1FormulaName_webfresh", (_split_size_limit) = 5];
}

message TPropRoot {
    option (NYT.default_field_flags) = SERIALIZATION_YT;
    option (NYT.default_field_flags) = OPTIONAL_LIST;

    optional double Acc = 1;
    optional bool ApplyBlender = 2;
    optional bool BsTouched = 3;
    map<string, string> ConfigInfo = 4 [(_compat_renamed_prefix) = "ConfigInfo_", (_split_size_limit) = 5];
    optional string DetectOrganicNews = 5;
    optional bool ErrorInSp = 6;
    optional string ExtensionsRankModel = 7 [(_split_size_limit) = 100];
    map<string, string> FormulaValueDump = 8 [(_compat_renamed_prefix) = "FormulaValueDump_", (_split_size_limit) = 5];
    optional string HostName = 9 [(_infinite_ttl) = true, (_rt_required) = true];
    optional uint64 Ig = 10;
    // TODO protobufize https://a.yandex-team.ru/arc/trunk/arcadia/search/web/extensions/rearrange/metric_signal_dumper/metric_signal_dumper.cpp
    map<string, string> MetricSignalDumper = 11 [(_split_size_limit) = 5];
    optional uint64 Nctx = 12;
    optional string RankingIntMn = 13 [(_split_size_limit) = 70];
    optional string RankingMn = 14 [(_split_size_limit) = 170];
    optional string RankingModel = 15 [(_split_size_limit) = 42];
    optional string RankingWords = 16 [(_split_size_limit) = 32];
    optional string RequestedRankingModel = 17 [(_split_size_limit) = 30];
    optional string ResponsedSources = 18 [(_split_size_limit) = 450];
    optional uint64 SourceTimestamp = 19;
    optional double SuperMindMult = 20;
    map<string, string> Unanswer = 21 [(_compat_renamed_prefix) = "Unanswer_", (_split_size_limit) = 700, (_ttl) = 90];
    map<string, string> VerticalCardConfig = 22 [(_split_size_limit) = 5];
    optional string Weather = 23;
    map<string, string> WebL3ModelVersionForExport = 24 [(_compat_renamed_prefix) = "WebL3ModelVersionForExport_", (_split_size_limit) = 5];
    optional string WebL3ModelsFlagsVersion = 25 [(_split_size_limit) = 5];
    optional bool YEda = 26;
    optional string YEdadeal = 27 [(_split_size_limit) = 5];
    map<string, string> Dumper = 28 [(_compat_renamed_prefix) = "Dumper.", (_split_size_limit) = 5, (_ttl) = 90];
    optional uint64 SuggestTagsCount = 29 [(_compat_renamed_from) = "suggest_tags_count"];
    optional bool AntirobotDegradation = 30 [(_compat_renamed_from) = "AntirobotDegradation"];
    optional string WebL3ModelVersionContextModelReformulations = 31 [(_compat_renamed_from) = "WebL3ModelVersionForExport_context_model_reformulations", (_split_size_limit) = 5];
    optional string WebL3ModelVersionNeuroTextNoTitleDssmLongClicksPredictor = 32 [(_compat_renamed_from) = "WebL3ModelVersionForExport_neuro_text_no_title_dssm_long_clicks_predictor", (_split_size_limit) = 5];
    optional string DumperMarket = 33 [(_compat_renamed_from) = "Dumper.Market", (_split_size_limit) = 5, (_ttl) = 90];
    optional double DumperMaxDocsInVideoWizardValue = 34 [(_compat_renamed_from) = "Dumper.MaxDocsInVideoWizard_value", (_split_size_limit) = 5, (_ttl) = 90];
    optional double DumperAbtFreshnessValue = 35 [(_compat_renamed_from) = "Dumper.abt_freshness_value", (_split_size_limit) = 5, (_ttl) = 90];
    optional double DumperImagesRightSurplusPredictorValue = 36 [(_compat_renamed_from) = "Dumper.images_right_surplus_predictor_value", (_split_size_limit) = 5, (_ttl) = 90];
    optional double DumperOrgMxValue = 37 [(_compat_renamed_from) = "Dumper.org_mx_value", (_split_size_limit) = 5, (_ttl) = 90];
    optional double DumperShinyDiscoveryReturnHideModelValue = 38 [(_compat_renamed_from) = "Dumper.shiny_discovery_return_hide_model_value", (_split_size_limit) = 5, (_ttl) = 90];
    optional bool DumperYdoProdFilterDefaultResult = 39 [(_compat_renamed_from) = "Dumper.ydo_prod_filter_default_result", (_split_size_limit) = 5, (_ttl) = 90];
    optional double DumperYdoProdFilterDefaultThreshold = 40 [(_compat_renamed_from) = "Dumper.ydo_prod_filter_default_threshold", (_split_size_limit) = 5, (_ttl) = 90];
    optional double DumperYdoProdFilterDefaultValue = 41 [(_compat_renamed_from) = "Dumper.ydo_prod_filter_default_value", (_split_size_limit) = 5, (_ttl) = 90];
    optional bool DumperYdoProdFilterSearchappResult = 42 [(_compat_renamed_from) = "Dumper.ydo_prod_filter_searchapp_result", (_split_size_limit) = 5, (_ttl) = 90];
    optional double DumperYdoProdFilterSearchappThreshold = 43 [(_compat_renamed_from) = "Dumper.ydo_prod_filter_searchapp_threshold", (_split_size_limit) = 5, (_ttl) = 90];
    optional double DumperYdoProdFilterSearchappValue = 44 [(_compat_renamed_from) = "Dumper.ydo_prod_filter_searchapp_value", (_split_size_limit) = 5, (_ttl) = 90];
    optional bool DumperYdoProdFilterTouchResult = 45 [(_compat_renamed_from) = "Dumper.ydo_prod_filter_touch_result", (_split_size_limit) = 5, (_ttl) = 90];
    optional double DumperYdoProdFilterTouchThreshold = 46 [(_compat_renamed_from) = "Dumper.ydo_prod_filter_touch_threshold", (_split_size_limit) = 5, (_ttl) = 90];
    optional double DumperYdoProdFilterTouchValue = 47 [(_compat_renamed_from) = "Dumper.ydo_prod_filter_touch_value", (_split_size_limit) = 5, (_ttl) = 90];
    optional string Unanswer0TIER = 48 [(_compat_renamed_from) = "Unanswer_0_TIER", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerAttributeIndex = 49 [(_compat_renamed_from) = "Unanswer_AttributeIndex", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerBANFILTERSAAS = 50 [(_compat_renamed_from) = "Unanswer_BANFILTER-SAAS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerBANFILTERSAASHAHN = 51 [(_compat_renamed_from) = "Unanswer_BANFILTER-SAAS_HAHN", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerBANFILTERSAASU = 52 [(_compat_renamed_from) = "Unanswer_BANFILTER-SAAS_U", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerBIGB = 53 [(_compat_renamed_from) = "Unanswer_BIGB", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerBIGBOUT = 54 [(_compat_renamed_from) = "Unanswer_BIGB_OUT", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerBLENDERCACHELOAD = 55 [(_compat_renamed_from) = "Unanswer_BLENDER_CACHE_LOAD", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerBLENDERSAASKNN = 56 [(_compat_renamed_from) = "Unanswer_BLENDER_SAAS_KNN", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerBertPersonalFactors = 57 [(_compat_renamed_from) = "Unanswer_BertPersonalFactors", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerCFGMODELS = 58 [(_compat_renamed_from) = "Unanswer_CFG_MODELS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerCfgModelsFactors = 59 [(_compat_renamed_from) = "Unanswer_CfgModelsFactors", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerCfgModelsSplitFactors = 60 [(_compat_renamed_from) = "Unanswer_CfgModelsSplitFactors", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerDYNTABLEHTTPPROXYBLENDER = 61 [(_compat_renamed_from) = "Unanswer_DYNTABLE_HTTP_PROXY_BLENDER", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerECOMSNIPSSAAS = 62 [(_compat_renamed_from) = "Unanswer_ECOMSNIPS-SAAS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerEmbeddingStorage = 63 [(_compat_renamed_from) = "Unanswer_EmbeddingStorage", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerFASTSNIPSSAAS = 64 [(_compat_renamed_from) = "Unanswer_FASTSNIPS-SAAS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerFASTSNIPSUSAAS = 65 [(_compat_renamed_from) = "Unanswer_FASTSNIPS_U-SAAS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerFASTQUERYSEARCHSAAS = 66 [(_compat_renamed_from) = "Unanswer_FAST_QUERYSEARCH_SAAS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerFactorsKeyInvService = 67 [(_compat_renamed_from) = "Unanswer_FactorsKeyInvService", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerGENERATIVEANSWERSDEGRADATIONSTATS = 68 [(_compat_renamed_from) = "Unanswer_GENERATIVE_ANSWERS_DEGRADATION_STATS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerInvertedIndexStorage = 69 [(_compat_renamed_from) = "Unanswer_InvertedIndexStorage", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerKeyInvService = 70 [(_compat_renamed_from) = "Unanswer_KeyInvService", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerMIDDLEHOSTDATASAAS = 71 [(_compat_renamed_from) = "Unanswer_MIDDLE_HOST_DATA_SAAS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerMODELSPROXY = 72 [(_compat_renamed_from) = "Unanswer_MODELS_PROXY", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerOFFLINEGENANSWER = 73 [(_compat_renamed_from) = "Unanswer_OFFLINE_GEN_ANSWER", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPLATINUM = 74 [(_compat_renamed_from) = "Unanswer_PLATINUM", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPLATINUMINT = 75 [(_compat_renamed_from) = "Unanswer_PLATINUMINT", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPLUTOMETA = 76 [(_compat_renamed_from) = "Unanswer_PLUTOMETA", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPREWEB = 77 [(_compat_renamed_from) = "Unanswer_PRE_WEB", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYBERTPERSONAL = 78 [(_compat_renamed_from) = "Unanswer_PROXY_BERT_PERSONAL", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYBERTPERSONALBLENDER = 79 [(_compat_renamed_from) = "Unanswer_PROXY_BERT_PERSONAL_BLENDER", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYCFGMODELS = 80 [(_compat_renamed_from) = "Unanswer_PROXY_CFG_MODELS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYCFGMODELSSPLIT = 81 [(_compat_renamed_from) = "Unanswer_PROXY_CFG_MODELS_SPLIT", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYDYNTABLEHTTPPROXYSOURCE = 82 [(_compat_renamed_from) = "Unanswer_PROXY_DYNTABLE_HTTP_PROXY_SOURCE", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYFETCHDOCDATA = 83 [(_compat_renamed_from) = "Unanswer_PROXY_FETCH_DOC_DATA", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYFETCHDOCDATAPLATINUM = 84 [(_compat_renamed_from) = "Unanswer_PROXY_FETCH_DOC_DATA_PLATINUM", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYFETCHDOCDATAQUICKSAMOHODONMIDDLE = 85 [(_compat_renamed_from) = "Unanswer_PROXY_FETCH_DOC_DATA_QUICK_SAMOHOD_ON_MIDDLE", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYFETCHDOCDATAWEB = 86 [(_compat_renamed_from) = "Unanswer_PROXY_FETCH_DOC_DATA_WEB", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYFETCHDOCDATAWEBFRESHONMIDDLE = 87 [(_compat_renamed_from) = "Unanswer_PROXY_FETCH_DOC_DATA_WEBFRESH_ON_MIDDLE", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYRTMODELS = 88 [(_compat_renamed_from) = "Unanswer_PROXY_RTMODELS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPROXYRTMODELSFEATURESPERSONALMODEL = 89 [(_compat_renamed_from) = "Unanswer_PROXY_RTMODELS_FEATURES_PERSONAL_MODEL", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerQUERYSEARCH = 90 [(_compat_renamed_from) = "Unanswer_QUERYSEARCH", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerQUICK = 91 [(_compat_renamed_from) = "Unanswer_QUICK", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerQUICKSAMOHODONMIDDLE = 92 [(_compat_renamed_from) = "Unanswer_QUICK_SAMOHOD_ON_MIDDLE", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerRANKINGMIDSAAS = 93 [(_compat_renamed_from) = "Unanswer_RANKING_MID-SAAS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerRANKINGMIDBATCHSAAS = 94 [(_compat_renamed_from) = "Unanswer_RANKING_MID_BATCH-SAAS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerRAPIDCLICKSCONVERSSAAS = 95 [(_compat_renamed_from) = "Unanswer_RAPID_CLICKS_CONVERS-SAAS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerREQUESTEXTENSIONSMETA = 96 [(_compat_renamed_from) = "Unanswer_REQUEST_EXTENSIONS_META", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerRTMODELSFEATURESPERSONALMODEL = 97 [(_compat_renamed_from) = "Unanswer_RTMODELS_FEATURES_PERSONAL_MODEL", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerRTMR = 98 [(_compat_renamed_from) = "Unanswer_RTMR", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerRTMRFACTORSAPI = 99 [(_compat_renamed_from) = "Unanswer_RTMR_FACTORS_API", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerRemoteStorage = 100 [(_compat_renamed_from) = "Unanswer_RemoteStorage", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerRtModelsFPMFactors = 101 [(_compat_renamed_from) = "Unanswer_RtModelsFPMFactors", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerRtModelsFactors = 102 [(_compat_renamed_from) = "Unanswer_RtModelsFactors", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerSERPDATASAAS = 103 [(_compat_renamed_from) = "Unanswer_SERPDATA-SAAS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerSUGGESTFACTS2 = 104 [(_compat_renamed_from) = "Unanswer_SUGGESTFACTS2", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerUGCDIGEST = 105 [(_compat_renamed_from) = "Unanswer_UGC_DIGEST", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerUGCFAVORITES = 106 [(_compat_renamed_from) = "Unanswer_UGC_FAVORITES", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerUSERHISTORYSAAS = 107 [(_compat_renamed_from) = "Unanswer_USER_HISTORY-SAAS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerVIDEOMYMOVIES = 108 [(_compat_renamed_from) = "Unanswer_VIDEO_MY_MOVIES", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerVIDEOUSERSETTINGS = 109 [(_compat_renamed_from) = "Unanswer_VIDEO_USER_SETTINGS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerWEATHERSERPICON = 110 [(_compat_renamed_from) = "Unanswer_WEATHER_SERP_ICON", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerWEB = 111 [(_compat_renamed_from) = "Unanswer_WEB", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerWEBFRESHONMIDDLE = 112 [(_compat_renamed_from) = "Unanswer_WEBFRESH_ON_MIDDLE", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerYABS = 113 [(_compat_renamed_from) = "Unanswer_YABS", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerYABSDIRECTVERTICAL = 114 [(_compat_renamed_from) = "Unanswer_YABS_DIRECT_VERTICAL", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerYABSDISTR = 115 [(_compat_renamed_from) = "Unanswer_YABS_DISTR", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerYABSPROXY = 116 [(_compat_renamed_from) = "Unanswer_YABS_PROXY", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerMain = 117 [(_compat_renamed_from) = "Unanswer_main", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerPlatinumLower = 118 [(_compat_renamed_from) = "Unanswer_platinum", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerWebLower = 119 [(_compat_renamed_from) = "Unanswer_web", (_split_size_limit) = 700, (_ttl) = 90];
    optional string UnanswerShinyDiscoveryDj = 120 [(_compat_renamed_from) = "Unanswer_SHINY_DISCOVERY_DJ", (_split_size_limit) = 700, (_ttl) = 90];
    optional uint64 PagerTrimTailRemoved = 121 [(_compat_renamed_from) = "Pager.Pager_trim_tail_removed"];
}
